### ISSUE TITLE
Support react@canary release

### ISSUE THREAD

**Issue by ellemedit** [rescript-lang/rescript-react#101]
React have plans to add new valid element/node type, hooks and APIs as react canary released.
I summarized that required for upcoming react canary things. Can we support these?

New React hooks and APIs are:
* [use](https://github.com/acdlite/rfcs/blob/first-class-promises/text/0000-first-class-support-for-promises.md#example-use-in-client-components-and-hooks): `(promise<'value> | context<'value>) => 'value`
  * I would suggest new type `valueContainer<'value>` to express above as they defined value container in RFC.
  * [TypeScript type binding](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/canary.d.ts#L31-L54)
* [cache](https://github.com/facebook/react/pull/25506): `'value => 'value`
  * [next.js docs](https://nextjs.org/docs/app/building-your-application/data-fetching/caching#react-cache)
  * TypeScript: `export function cache<CachedFunction extends Function>(fn: CachedFunction): CachedFunction`
* ~~useTransition~~ (already bound, just ignore)
* ~~useDeferredValue~~ (already bound, just ignore)
* [startTransition](https://react.dev/reference/react/startTransition): `((. unit => unit) => unit)`

New ReactDOM hooks and APIs are:
* [flushSync](https://react.dev/reference/react-dom/flushSync): `((. unit => unit) => unit)`
* [experimental_useFormStatus](https://github.com/facebook/react/pull/26722): `(unit => { pending: boolean, action: promise<void> | (data: FormData) => unit, method: string, data: FormData })`
  * [next.js docs](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#experimental-useformstatus)
* [experimental_useOptimistic](https://github.com/facebook/react/pull/26740): `(@uncurry ('state, ('state, 'action) => 'state)) => ('state, ('action) => unit)`
  * [next.js docs](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#experimental-useoptimistic)
  * `State` postfix removed from another PR.

[Client Action Function Support](https://github.com/facebook/react/pull/26674): `string | (formData: FormData) => unit`
* `<button formAction={(formData) => { ... }} />`
* `<form action={(formData) => { ... }} />`

[Async component](https://github.com/acdlite/rfcs/blob/first-class-promises/text/0000-first-class-support-for-promises.md#example-await-in-server-components):

rescript input:

```rescript
type user = {id: string, name: string}
let fetchUserById = async (userId) => {
  {
    id: userId,
    name: Js.Float.toStringWithRadix(Js.Math.random(), ~radix=16),
  }
}

@react.component
let make = async (~userId) => {
  let user = await fetchUserById(userId)
  <div> {React.string(user.name)} </div>
}
```

Async component JS output expectation:

```js
import * as JsxRuntime from "react/jsx-runtime";
async function fetchUserById(userId) {
  return { id: userId, name: Math.random().toString(16) };
}
async function Playground(props) {
  var user = await fetchUserById(props.userId);
  return JsxRuntime.jsx("div", { children: user.name });
}
var make = Playground;
export { fetchUserById, make };
```

New valid node:

[Promise node](https://github.com/facebook/react/pull/25634):

```rescript
type user = {id: string, name: string}
let fetchUserById = async (userId) => {
  {
    id: userId,
    name: Js.Float.toStringWithRadix(Js.Math.random(), ~radix=16),
  }
}

let fetchUserNameById = async (userId) => {
  let user = await fetchUserById(userId)
  user.name
}

@react.component
let make = (~userId) => {
  let userName = fetchUserNameById(userId)
  <React.Suspense>
    {React.promise(userName)}
  </React.Suspense>
}
```

expect output:

```jsx
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
async function fetchUserById(userId) {
  return { id: userId, name: Math.random().toString(16) };
}
async function fetchUserNameById(userId) {
  return (await fetchUserById(userId)).name;
}
function Playground(props) {
  var userName = fetchUserNameById(props.userId);
  return JsxRuntime.jsx(React.Suspense, { children: userName });
}
var make = Playground;
export { fetchUserById, fetchUserNameById, make };
```

[React.Context node](https://github.com/facebook/react/pull/25641)

---

thank you for reading this.

**Comment by mununki** [comment]
Can you add a references about the new apis, async component and promise node?

**Comment by Beingbook** [comment]
I’ll update with link PR and docs for each changes.

**Comment by Beingbook** [comment]
@mununki I attached link to body and added context node too.

**Comment by Beingbook** [comment]
I don't know `FormData` exists in @rescript/react. perhaps it should be referenced to https://github.com/TheSpyder/rescript-webapi ?

**Comment by Beingbook** [comment]
Please understand replacing next.js reference and PR instead official documentation, canary release doesn't have official documentation as React core team said.

**Comment by mununki** [comment]
What about putting this on the forum(https://forum.rescript-lang.org/) and have a further community discussion about it?
