### ISSUE TITLE
Notes on apis

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/rescript-react#11]
- `ReactDOMRe.objToDOMProps` -> this function is currently missing, probably need to add that back for the transition (later on we will not need that apis for v1 afaik)

**Upgrade notes:**

- `ReasonReact.reactElement` -> `React.element`
- `ReactDOMRe.Style` -> `ReactDOM.Style`
- `ReactDOMRe.props` -> `ReactDOM.props`
- `ReasonReact.string`, `ReasonReact.int`,... -> `React.string`, `React.int`,...

**Comment by chenglou** [comment]
Uncurried, Event's `foo["bar"]` usage

**Comment by cknitt** [comment]
Closing this issue, as it is about the past transition from reason-react to @rescript/react that happened 1 1/2 years ago.
