### ISSUE TITLE
Empty Fragments (<></>) no longer work

### ISSUE THREAD

**Issue by benfaerber** [rescript-lang/rescript-react#110]
```rescript
@react.component
let make = (~title: string) => {
    <div>
        {switch title {
        | "" => <></>
        | myTitle => <h2>{React.string(title)}</h2>
        }}
    </div>
}
```

After updating to rescript 11 and rescript react 11, empty fragments no longer work even if they have something inside them (like a react string). Replacing it with `React.Fragment` works.
It gives a slightly cryptic error message: `Empty record literal {} should be type annotated or used in a record context.`

Is this an issue with the JSX parser or did I miss something in the migration notes?

**Comment by fhammerschmidt** [comment]
What's ReScript-React 11?
The minimum required version for ReScript 11 is ReScript-React 0.12.
https://rescript-lang.org/docs/manual/latest/migrate-to-v11#compiler-libraries

Your code compiles fine [in the playground](https://rescript-lang.org/try?version=v11.0.0&code=AIJwpghgxgLgdFA9gWwA6IHZgzAUAGzBgAJkIBrMYgXmIAoA-GASxkIC5iBnGEZjAOYBKGgD5iAb1zFiAHgAmzAG6jpMyVwDurKAAtiLNlSnriAH2IAiS2LnjZAelWmLyAJ4AVVoVuzdAJnEJACVIWDgePkE6Q0IhAF85BwDndXj4tUdFFVwMoA) which uses the most current versions.

**Comment by benfaerber** [comment]
It turns out I was on using this version (https://github.com/rescript-lang/rescript-react/releases/tag/v0.11.0). My mistake! After updating to version 12 fragments work as expected. Thanks for the help!
