### ISSUE TITLE
Docs Broken

### ISSUE THREAD

**Issue by jarednorman** [rescript-lang/rescript-react#123]
I'm not sure if this is the best place to report it, but the link in the README to the [Introduction](https://rescript-lang.org/docs/react/latest/introduction) currently leads to a blank page. I've tested on a couple of devices/browsers, disabled adblocker, et cetera, so I'm pretty sure it's not just me.

Firefox screenshot:

![CleanShot 2024-12-28 at 11 56 17@2x](https://github.com/user-attachments/assets/10743691-8d6d-44c3-b222-d05cfe70aef2)

**Comment by jarednorman** [comment]
Other pages seem to be broken as well, and this only seems to affect the ReScript React docs on the site. No issues with any of the other docs.

**Comment by fhammerschmidt** [comment]
Thanks for making me aware. It should work again in a minute.
