### ISSUE TITLE
Props overwritten when they have the same prefix followed by underscores

### ISSUE THREAD

**Issue by nireno** [rescript-lang/rescript-react#17]
This rescript component:

```
@react.component
let make = (
  ~foo__one,
  ~foo__two,
) => {
  <div>
    {foo__one->React.string}
    {foo__two->React.string}
  </div>
}
```

Generates this javascript function:

```
function Playground(Props) {
  var foo__one = Props.foo;
  var foo__two = Props.foo;
  return React.createElement("div", undefined, foo__one, foo__two);
}
```
Notice that `foo__one` and `foo__two` are both assigned the value of `Props.foo`.
The result is that the value passed for `~foo__one` get's rendered twice and `~foo_two` is ignored.

It would be helpful if this at least generated a warning.

**Comment by cristianoc** [comment]
++ @rickyvetter is this for the JSX ppx?

**Comment by mattdamon108** [comment]
Yes, this issue is gone with v4
```js
function Underscore(props) {
  return React.createElement("div", undefined, props.foo__one, props.foo__two);
}
```

**Comment by cknitt** [comment]
@mattdamon108 Ok, then I would suggest to close this issue as fixed in v4 (unless you would like to spend time on fixing this in the v3 PPX).
