### ISSUE TITLE
Add support for `ReactEvent.Keyboard.stopImmediatePropagation` binding

### ISSUE THREAD

**Issue by sinap-fb** [rescript-lang/rescript-react#24]

**Comment by cknitt** [comment]
@sinap-fb Are you sure that this actually exists on React Synthetic Events?

It is neither in the React docs (https://reactjs.org/docs/events.html) nor in the TypeScript typedefs (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts).

I think it only exist on the underlying nativeEvent, but that is currently only typed as

```rescript
  @get external nativeEvent: Type.t => {..} = "nativeEvent" /* Should return Dom.event */
```

Also it is not Keyboard-specific as far as I can see.

**Comment by cknitt** [comment]
Closing. @sinap-fb feel free to ping me if this is still relevant for you.
