### ISSUE TITLE
How to use aria-current?

### ISSUE THREAD

**Issue by hellpirat** [rescript-lang/rescript-react#28]
Why this prop is under comment - https://github.com/rescript-lang/rescript-react/blob/master/src/ReactDOM.res#L1091  ?

```
 <li className="px-4 text-gray-700" ariaCurrent="page"> {"Blog"->React.string} </li>

This argument cannot be applied with label ~ariaCurrent
```

**Comment by ryyppy** [comment]
Back then there was no way to seamlessly map this from ReScript to JavaScript. Now with poly-variants mapping to strings, it should be possible to map these attributes.

**Comment by cknitt** [comment]
See also https://github.com/rescript-lang/rescript-compiler/issues/5708.

**Comment by cknitt** [comment]
Done in https://github.com/rescript-lang/rescript-compiler/pull/5723.
