### ISSUE TITLE
v0.10 Release Tasks

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/rescript-react#3]
- [x] Port to ReScript syntax
- [x] Align naming / terminologies
- [x] Remove legacy code (see Changes.md for details)
- [x] Upgrade to bs-platform@8.4
- [x] Align upcoming docs for `rescript-react@0.10` (available [here](https://rescript-lang.org/docs/react/latest/introduction))
- [ ] Write migration-guide for `reason-react@0.9` -> `rescript-react@0.10`
- [x] Try `rescript-react` in existing codebases before official release
- [x] Release `rescript-react@0.10`
- [x] Add a note on `reason-react` for new users

**Comment by cknitt** [comment]
@ryyppy can this be closed? Probably a bit late now anyway for the migration guide as 0.10.3 was published in May 2021...
