### ISSUE TITLE
Why not useImperativeHandle exists?

### ISSUE THREAD

**Issue by thomaszdxsn** [rescript-lang/rescript-react#32]
does any implementation diffcult?

**Comment by rickyvetter** [comment]
I think it's more about ForwardRef being incredibly difficult to type/work with and generally being discouraged (in rescript-react at least) as opposed to just passing refs as props with any other name. I would rather not encourage this. If there was a usecase outside of ForwardRef I would be open to it. Closing for now, but feel free to reopen if you have questions or other usecases.
