### ISSUE TITLE
React@18 support

### ISSUE THREAD

**Issue by bloodyowl** [rescript-lang/rescript-react#34]
## Context

React 18 is in RC and will soon be released:

https://github.com/reactwg/react-18/discussions/112

## Updates

- Deprecate `ReactDOM.render`
- `ReactDOM.Experimental.createRoot` → `ReactDOM.createRoot`
- ~~`ReactDOM.Experimental.createBlockingRoot`~~
- `ReactDOM.Experimental.root` → `ReactDOM.Root.t`
- `ReactDOM.Experimental.render` → `ReactDOM.Root.render`
- `ReactDOM.Root.unmount`
- `React.useDeferredValue`
- `React.useInsertionEffect{,0,1,2,3,4,5,6,7}`
- `React.useSyncExternalStore`
- `React.useId`

**Comment by tom-sherman** [comment]
I believe this list is missing `startTransition`?

**Comment by cometkim** [comment]
I have binding to `useMutableSource` (former version of `useSyncExternalStore`)

https://github.com/reason-seoul/snowpack-rescript-react/blob/07a59a6/src/bindings/ReactExperimental.res#L4-L26

guess it might help
