### ISSUE TITLE
`onReset` is not allowed on form properties

### ISSUE THREAD

**Issue by gaeulbyul** [rescript-lang/rescript-react#37]
rescript-react doesn't allow `onReset` prop on `<form>` element. (I think it should allow?)

[Example](https://rescript-lang.org/try?code=DYUwLgBA9gdgygVwEYFsCWkC8EQDcQxYB8EA3gFAQQBSAzgHTBQDmAFAES3LphggAm7AJTkAvuXKhIsAEoha4CNjwFiZSjQZM27AE7zwfQSPHkAAvoCGAYzD1rUFAAdYqyYpSWA1iCURWQkokFFQAPABmULoo0PDcGLFyCmBEGmFoME4IkGAAnk4gAPqYnPFg7BC4lsAIICWIqBgVAPSpVOmZ2RB5BcV6BuWV1bUlSeAtbRChzZHRqeJAA):

```rescript
let onSubmit = event => {
  Js.log("submitted")
}

let onReset = event => {
  Js.log("resetted")
}

@react.component
let make = () => {
  <form onSubmit onReset>
    <input type_="submit" value="Submit" />
    <input type_="reset" value="Reset" />
  </form>
}
```

Error:
```
[E] Line 11, column 17:
The function applied to this argument has type
    (
  ~?key: string,
  ~?ref: ReactDOM.domRef,
  /* skip */
) => ReactDOM.Props.domProps
This argument cannot be applied with label ~onReset
```

**Comment by cknitt** [comment]
This is now fixed in `JsxDOM.domProps` in the compiler repo, see https://github.com/rescript-lang/rescript-compiler/pull/5711.
