### ISSUE TITLE
JSX Changes

### ISSUE THREAD

**Issue by rickyvetter** [rescript-lang/rescript-react#39]
This is a cross-repo change and so I want to have a place here to comment/get feedback from folks.

In particular I want to remember to take a look at all of the issues/prs tagged `html attribute change` #38 will land since it's a bug but still needs to be ported over.

**Comment by zth** [comment]
Is the other repo the syntax repo?

**Comment by rickyvetter** [comment]
Yup! Here's a (very rough) draft of changes I've chatted about. Needs some cleanup before it's ready for prime time.

**Comment by cknitt** [comment]
@Kingdutch DOM props are now defined as `JsxDOM.domProps` here in the compiler repo: https://github.com/rescript-lang/rescript-compiler/blob/10.1_release/jscomp/others/jsxDOM.res.

@rickyvetter Closing this issue, as the JSX 4 changes are well underway / almost finished and documented here: https://github.com/rescript-lang/syntax/blob/master/cli/JSXV4.md
