### ISSUE TITLE
Expose ReactDOM.Props.domProps separately and concat?

### ISSUE THREAD

**Issue by AlexMoutonNoble** [rescript-lang/rescript-react#52]
Hi All
I am trying to compactly wrap a native input using createDOMElementVariadic, since input props are expansive and who wants to repeat all that.   I notice that createDOMElementVariadic takes domProps, but that domProps and props are both @deriving(abstract) in the same module, so the accessors for domProps are shadowed.  Also, with the types being abstract I can't add props to an existing domProps.

How does a PR for separating domProps to its own module and providing a `concat` operator sound?

**Comment by mattdamon108** [comment]
Can you elaborate on your intention with an example? What prop do you want to add? Anyway, with V10.*, the new `JsxDOM` module is opt-in, so you can do something like this.
<img width="285" alt="image" src="https://user-images.githubusercontent.com/36963424/180648047-a2345124-3f42-478d-a4a1-fe05215c9145.png">
If the new version of rescript-react is released, `ReactDOM` is bound to `JsxDOM`.  You can use it together with the new jsx ppx v4.

**Comment by cknitt** [comment]
Yes, this should be resolved with JSX v4, closing.
