### ISSUE TITLE
ReactDOMServer.renderToString ... server.js not exported from react-dom

### ISSUE THREAD

**Issue by AlexMoutonNoble** [rescript-lang/rescript-react#55]
Hi Folks.
Just came across this problem in porting some existing js to rescript.
If i reimplement the renderToString bindings without the "js" suffix on the module, it seems to work fine.
Maybe a simple change to remove the suffix there?

Can make a PR if that seems reasonable

Thanks
Alex

**Comment by cknitt** [comment]
Fixed in #44.
