### ISSUE TITLE
port zero-cost-rescript example

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/rescript-react#7]
There are some breaking changes when porting over https://github.com/bobzhang/zero-cost-rescript from `reason-react`.

Good data points for some legacy api usage (also good for writing migration guide).

**Comment by bobzhang** [comment]
done in that repo

**Comment by cknitt** [comment]
Closing this issue, as it is about the past transition from reason-react to @rescript/react that happened 1 1/2 years ago.
