### ISSUE TITLE
V3 compatibility does not seem to work with lowercase JSX

### ISSUE THREAD

**Issue by cristianoc** [rescript-lang/rescript-react#70]
Example (built in v3 mode):

```rescript
open ReactV3
let _ = <div name="" /> // The value domProps can't be found in ReactDOMRe
```

CC @mattdamon108

**Comment by mattdamon108** [comment]
Can you share the deps? compiler and rescript-react?

**Comment by cristianoc** [comment]
```
"rescript": "^10.1.0-rc.2"
"@rescript/react": "^0.11.0-rc.1"
```

**Comment by mattdamon108** [comment]
I’ll check and let you know.

**Comment by mattdamon108** [comment]
I think this error is caused by removing `include ReactDOM.Props` https://github.com/rescript-lang/rescript-react/pull/65/files which is still used by V3. I think I need to revert it `include ReactDOM_V3.Props` back to fix the build issue.
What do you think? @cknitt

**Comment by cknitt** [comment]
If it's only about this one type, then I'd prefer to just add

```
type domProps = ReactDOM_V3.domProps
```

to `legacy/ReactDOMRe.res`.

**Comment by mattdamon108** [comment]
> If it's only about this one type, then I'd prefer to just add
> 
> ```
> type domProps = ReactDOM_V3.domProps
> ```
> 
> to `legacy/ReactDOMRe.res`.

Good point. I’ll make a PR to fix it.
How about adding the old type props either?

```rescript
type props = ReactDOM_V3.Props.props
```

**Comment by cknitt** [comment]
Not sure if it is required, but I guess it won't hurt.

So
```rescript
type domProps = ReactDOM_V3.Props.domProps
type props = ReactDOM_V3.Props.props
```

or equivalently, as there is an `include Props` in `ReactDOM_V3`:

```rescript
type domProps = ReactDOM_V3.domProps
type props = ReactDOM_V3.props
```

**Comment by mattdamon108** [comment]
I've run some tests, I found the type alias won't work. Only `include ReactDOM_V3.Props` fixes the issue, because the type alias is not working `@derving(abstract)`. That's why the error msg was complaining about the value of domProps instead of type domProps.

**Comment by cknitt** [comment]
Ah, right, sorry, had not noticed that in the error message.

**Comment by mattdamon108** [comment]
@cristianoc Can you check whether the issue is gone?
