### ISSUE TITLE
Any plan to support `React.lazy`?

### ISSUE THREAD

**Issue by pd4d10** [rescript-lang/rescript-react#81]
To be used with `React.Suspense`

https://reactjs.org/docs/react-api.html#reactlazy

> Update: found this PR https://github.com/rescript-lang/rescript-compiler/pull/5703 dynamic import implementation, probably related

**Comment by cknitt** [comment]
Yes, dynamic import is finally here thanks to @mununki and `React.lazy` works with it as describe here:
https://github.com/rescript-lang/rescript-compiler/issues/6223#issuecomment-1530925131 🎉

Will add it to rescript-react in the next days.
