### ISSUE TITLE
Can I use async in event handler?

### ISSUE THREAD

**Issue by Tolluset** [rescript-lang/rescript-react#84]
I want to use it to add the async in the onClick handler. But the compiler wants a `unit` return type.

```res

let onClick = async _evt => {
  open Fetch
  open Promise

  let url = "https://jsonplaceholder.typicode.com/todos/1"

  let res = await fetch(url)->then(Response.json)
}

...

<button onClick> {"get todos"->React.string} </button>
```

```res
This has type: JsxEvent.Mouse.t => promise<unit>
Somewhere wanted: JsxEvent.Mouse.t => unit

The incompatible parts:
  promise<unit> vs unit
```

So, I tried to change the return type `unit` type to `promise<unit>` in the ReactDom file in my local node_modules.

https://github.com/rescript-lang/rescript-react/blob/78893fbe9a49bb39a470b7431415ef6529858332/src/ReactDOM.res#L451-L453

```res
    /* Mouse events */
    @optional
    onClick: ReactEvent.Mouse.t => promise<unit>,
```

But, It complains still.

I thought a simple workaround was just using `Obj.magic` like

```res
<button onClick={Obj.magic(onClick)}> {"get todos"->React.string} </button>
```

and, it worked.

Is there any good workaround for this situation?

Use async event handler is not good or just not dealt with binding?

**Comment by Tolluset** [comment]
I made workaround

```res
type asyncMouseHandler<'a> = JsxEvent.Mouse.t => promise<'a>
type noramlMouseHandler = JsxEvent.Mouse.t => unit

external makeNoramlMouseHandler: asyncMouseHandler<'a> => noramlMouseHandler = "%identity"

...

<button onClick={onClick->makeNoramlMouseHandler}> {"get todos"->React.string} </button>
```

it worked... But look not so good...

**Comment by heng1025** [comment]
maybe wrap `ignore` looks good.

```jsx
<button onClick={_=>onClick()->ignore}> {"get todos"->React.string} </button>
```

**Comment by Tolluset** [comment]
> maybe wrap `ignore` looks good.
> 
> ```js
> <button onClick={_=>onClick()->ignore}> {"get todos"->React.string} </button>
> ```

Thanks! At that time, I didn't recognize 😅
