### ISSUE TITLE
publish 11.0 to npm?

### ISSUE THREAD

**Issue by AlexMoutonNoble** [rescript-lang/rescript-react#85]
Hi all
I see 11.0 tagged, but isnt up on npm.  
Can that go up?  Waiting on jsx4.something?

I notice that React.Context examples on website no longer compile in rescript-lang.org/try and wondering where to start.

Thanks!
A

**Comment by cknitt** [comment]
I think it was probably on npm as `next` at the time? In the meantime it is already tagged as `latest`.
